Ultralight EV1/NTAG new dump format supports with new GUI compiled
iceman1001/ChameleonMini-rebooted pull request #109
Opened 2019-08-03 18:45 UTC by McEloff

1. Ultralight/EV1/NTAG simulation now checks counters, tearing flags, signature from new dump format
2. New compiled GUI supported new dump format for Ultralight EV1/NTAG

2019-08-03 19:56 UTC, iceman1001 requested changes
Nice addition of new MFU dumps format.
We don't add the binary of the GUI to this repo.  You will have to remove that one.

2019-08-03 19:56 UTC, iceman1001 commented on Firmware/Chameleon-Mini/Application/MifareUltralight.c
> +                MemoryReadBlock(&Counter, (PageCount + CounterId) * MIFARE_ULTRALIGHT_PAGE_SIZE, 3);
Don't use numbers.  Use a define macro / const,  to increase maintainability.

2019-08-03 19:56 UTC, iceman1001 commented on Firmware/Chameleon-Mini/Application/MifareUltralight.c
> +                MemoryWriteBlock(&Counter, (PageCount + CounterId) * MIFARE_ULTRALIGHT_PAGE_SIZE, 3);
same as above

2019-08-03 19:56 UTC, iceman1001 commented on Firmware/Chameleon-Mini/Application/MifareUltralight.c
> +                }
better detection of old vs new format will be needed.

2019-08-03 19:56 UTC, iceman1001 commented on Firmware/Chameleon-Mini/Application/MifareUltralight.c
> +                MemoryReadBlock(Buffer, (PageCount + CounterId) * MIFARE_ULTRALIGHT_PAGE_SIZE + 3, 1);
same as above

2019-08-12 20:41 UTC, iceman1001 commented
@shinhub  @bogiton   Have you guys tested this one? 
I am not interested in adding the win gui binaries on this repo but the functionality I want.

2019-08-12 22:06 UTC, shinhub commented
Sorry, do not have any Ultralight application at hand for now...

2019-08-14 00:20 UTC, iceman1001 commented
@McEloff   I like the functionality  but we are not adding GUI binaries into this repo.  You will need to remove that part.

2019-08-14 17:36 UTC, merged